site_name: Cluster Test Wiki
dev_addr: "127.0.0.1:8008"

theme:
  name: readthedocs
  highlightjs: true


nav:
  - Overview:
      - Introduction: 'overview/introduction.md'
  - Cluster Probe:
      - Requirements: 'cluster-probe/requirements.md'
      - Implementation: 'cluster-probe/implementation.md'
      - Design: 'cluster-probe/design.md'
      - Testing: 'cluster-probe/testing.md'
      - User guide: 'cluster-probe/user-guide.md'
      - Api specification: 'cluster-probe/api-specification.md'
  - Probe Builder:
      - Requirements: 'probe-builder/introduction.md'
      - Design: 'probe-builder/design.md'
      - Implementation: 'probe-builder/implementation.md'
      - Testing: 'probe-builder/testing.md'
      - User guide: 'probe-builder/user-guide.md'
      - Api specification: 'probe-builder/api-specification.md'